# Generated by Django 6.0.6 on 2026-07-26 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('Clinic', 'Clinic'), ('Nursing Home', 'Nursing Home'), ('Hospital', 'Hospital'), ('Other', 'Other')], max_length=50)),
                ('bed_capacity', models.PositiveIntegerField(blank=True, help_text='Number of beds', null=True)),
                ('interested_package', models.CharField(blank=True, choices=[('Essential', 'Essential'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Not sure yet', 'Not sure yet')], max_length=50)),
                ('preferred_date', models.DateTimeField()),
                ('message', models.TextField(blank=True, help_text='Additional information about facility needs')),
                ('is_contacted', models.BooleanField(default=False, help_text='Has the team contacted this lead?')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.IntegerField(default=0, help_text='Order in which FAQs appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name e.g., MediCore Essential', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short description under package name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the package')),
                ('price', models.CharField(help_text="Setup fee in KES (e.g., '50,000')", max_length=20)),
                ('price_prefix', models.CharField(blank=True, default='', help_text="e.g., 'From '", max_length=20)),
                ('monthly_sla', models.CharField(help_text="Monthly SLA fee in KES (e.g., '5,000')", max_length=20)),
                ('monthly_sla_prefix', models.CharField(blank=True, default='', help_text="e.g., 'From '", max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured/most popular')),
                ('badge_text', models.CharField(blank=True, help_text="e.g., 'Most Popular'", max_length=50)),
                ('modules_label', models.CharField(blank=True, default='All Included Modules', help_text='Custom label for modules section', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which packages appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=120, unique=True)),
                ('short_description', models.CharField(help_text='Brief description shown on services grid', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Full detailed description')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-solid fa-heart-pulse')", max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Service image', null=True, upload_to='services/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which services appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Setting key e.g., 'support_phone'", max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value')),
                ('description', models.CharField(blank=True, help_text='Description of what this setting controls', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of team member', max_length=100)),
                ('role', models.CharField(help_text='Job title/position', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Profile image', null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which team members appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Module name', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which modules appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.package')),
            ],
            options={
                'verbose_name': 'Package Module',
                'verbose_name_plural': 'Package Modules',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
